Remove type annotation stubs (#412)
My type annotation stubs made it upstream!
https://github.com/python/typeshed/pull/4480

But then I had to install `types-redis` because running Mypy 0.901 gave
me these error messages:

```
Running static type checks
pottery/exceptions.py:22: error: Library stubs not installed for "redis" (or incompatible with Python 3.9)
pottery/monkey.py:37: error: Library stubs not installed for "redis" (or incompatible with Python 3.9)
pottery/base.py:45: error: Library stubs not installed for "redis" (or incompatible with Python 3.9)
pottery/base.py:45: note: Hint: "python3 -m pip install types-redis"
pottery/base.py:45: note: (or run "mypy --install-types" to install all missing stub packages)
pottery/base.py:45: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
pottery/base.py:47: error: Library stubs not installed for "redis.client" (or incompatible with Python 3.9)
pottery/set.py:28: error: Library stubs not installed for "redis" (or incompatible with Python 3.9)
pottery/set.py:29: error: Library stubs not installed for "redis.client" (or incompatible with Python 3.9)
pottery/redlock.py:52: error: Library stubs not installed for "redis" (or incompatible with Python 3.9)
pottery/redlock.py:54: error: Library stubs not installed for "redis.client" (or incompatible with Python 3.9)
pottery/nextid.py:37: error: Library stubs not installed for "redis" (or incompatible with Python 3.9)
pottery/nextid.py:39: error: Library stubs not installed for "redis.client" (or incompatible with Python 3.9)
pottery/list.py:30: error: Library stubs not installed for "redis" (or incompatible with Python 3.9)
pottery/list.py:32: error: Library stubs not installed for "redis.client" (or incompatible with Python 3.9)
pottery/hyper.py:25: error: Library stubs not installed for "redis" (or incompatible with Python 3.9)
pottery/dict.py:31: error: Library stubs not installed for "redis" (or incompatible with Python 3.9)
pottery/dict.py:32: error: Library stubs not installed for "redis.client" (or incompatible with Python 3.9)
pottery/deque.py:25: error: Library stubs not installed for "redis" (or incompatible with Python 3.9)
pottery/deque.py:26: error: Library stubs not installed for "redis.client" (or incompatible with Python 3.9)
pottery/counter.py:30: error: Library stubs not installed for "redis.client" (or incompatible with Python 3.9)
pottery/cache.py:36: error: Library stubs not installed for "redis" (or incompatible with Python 3.9)
pottery/cache.py:37: error: Library stubs not installed for "redis.exceptions" (or incompatible with Python 3.9)
Found 20 errors in 12 files (checked 18 source files)
```