Don't auto-release Redlock on instance destruction
This PR effectively reverts this one: https://github.com/brainix/pottery/pull/272

When I deployed this to production, I started seeing these tracebacks in
the logs:

    rajiv.shah@RajivsMacBookPro spool % heroku run python3 manage.py renumber_popularity
    Running python3 manage.py renumber_popularity on ⬢ spool... up, run.4291 (Hobby)
    [2020-11-23 00:46:42,717] INFO in stooges: renumber_popularity() held redlock:popularity for 38 ms
    Exception ignored in: <function Redlock.__del__ at 0x7f5aa68db8b0>
    Traceback (most recent call last):
      File "/app/.heroku/python/lib/python3.9/site-packages/pottery/redlock.py", line 472, in __del__
        self.__release()
      File "/app/.heroku/python/lib/python3.9/site-packages/pottery/redlock.py", line 409, in release
        futures.add(executor.submit(self.__release_master, master))
      File "/app/.heroku/python/lib/python3.9/concurrent/futures/thread.py", line 163, in submit
        raise RuntimeError('cannot schedule new futures after '
    RuntimeError: cannot schedule new futures after interpreter shutdown

On second thought, the Redlock's timeout should be enough to preserve
liveness; we don't need to also auto-release Redlock on instance
destruction.